<% if (ENV['REDIS_QUEUE_URL'] || ENV['REDIS_URL']) %>
default: &default
  adapter: redis
  url: <%= (ENV['REDIS_QUEUE_URL'] || ENV['REDIS_URL']) %>
  channel_prefix: loomio
<% else %>
default: &default
  adapter: postgresql
<% end %>

production: *default
development: *default
test:
  adapter: postgresql
