poll:
  - "#70C9F8"
  - "#C8E56E"
  - "#D38FE1"
  - "#999FDE"
  - "#FA8295"
  - "#97D298"
  - "#C19A93"
  - "#F68AC6"
proposal:
  - "#00D177"
  - "#F6A82B"
  - "#F96168"
  - "#CE261B"
count:
  - "#1CA9F4"
  - "#DDDDDD"
dot_vote:
  - "#70C9F8"
  - "#C8E56E"
  - "#D38FE1"
  - "#999FDE"
  - "#FA8295"
  - "#97D298"
  - "#C19A93"
  - "#F68AC6"
meeting:
  - "#70C9F8"
  - "#C8E56E"
  - "#D38FE1"
  - "#999FDE"
  - "#FA8295"
  - "#97D298"
  - "#C19A93"
  - "#F68AC6"

missing: "#FF0000"
