blank:
  process_name_i18n: discussion_templates.blank.process_name
  process_subtitle_i18n: discussion_templates.blank.process_subtitle
  process_introduction_format: html
  description_format: html
  newest_first: false
  max_depth: 3
  position: 0

discuss_a_topic:
  title_placeholder_i18n: discussion_templates.discuss_a_topic.title_placeholder
  process_name_i18n: discussion_templates.discuss_a_topic.process_name
  process_subtitle_i18n: discussion_templates.discuss_a_topic.process_subtitle
  process_introduction_i18n: discussion_templates.discuss_a_topic.process_introduction
  process_introduction_format: html
  description_i18n: discussion_templates.discuss_a_topic.description
  description_format: html
  recipient_audience: group
  newest_first: false
  max_depth: 3
  position: 1
  recipient_audience: group

onboarding_to_loomio:
  title_i18n: discussion_templates.onboarding_to_loomio.title
  process_name_i18n: discussion_templates.onboarding_to_loomio.process_name
  process_subtitle_i18n: discussion_templates.onboarding_to_loomio.process_subtitle
  process_introduction_i18n: discussion_templates.onboarding_to_loomio.process_introduction
  process_introduction_format: html
  description_i18n: discussion_templates.onboarding_to_loomio.description
  tags_i18n:
  - discussion_templates.onboarding_to_loomio.onboarding
  newest_first: false
  max_depth: 3
  position: 2
  recipient_audience: group

advice_process:
  title_placeholder_i18n: discussion_templates.advice_process.title_placeholder
  process_name_i18n: discussion_templates.advice_process.process_name
  process_subtitle_i18n: discussion_templates.advice_process.process_subtitle
  process_introduction_i18n: discussion_templates.advice_process.process_introduction
  description_i18n: discussion_templates.advice_process.description
  tags_i18n: 
  - discussion_templates.advice_process.advice
  description_format: html
  process_introduction_format: html
  newest_first: false
  position: 3
  max_depth: 3
  recipient_audience: group

consent_process:
  title_placeholder_i18n: discussion_templates.consent_process.title_placeholder
  process_name_i18n: discussion_templates.consent_process.process_name
  process_subtitle_i18n: discussion_templates.consent_process.process_subtitle
  process_introduction_i18n: discussion_templates.consent_process.process_introduction
  description_i18n: discussion_templates.consent_process.description
  tags_i18n: 
  - discussion_templates.consent_process.consent
  process_introduction_format: html
  description_format: html
  newest_first: false
  position: 3
  max_depth: 3
  recipient_audience: group

decision_by_consensus:
  title_placeholder_i18n: discussion_templates.decision_by_consensus.title_placeholder
  process_name_i18n: discussion_templates.decision_by_consensus.process_name
  process_subtitle_i18n: discussion_templates.decision_by_consensus.process_subtitle
  process_introduction_i18n: discussion_templates.decision_by_consensus.process_introduction
  description_i18n: discussion_templates.decision_by_consensus.description
  tags_i18n: 
  - discussion_templates.decision_by_consensus.consensus
  process_introduction_format: html
  description_format: html
  newest_first: false
  position: 4
  max_depth: 3
  recipient_audience: group
  
approve_a_document:
  title_placeholder_i18n: discussion_templates.approve_a_document.title_placeholder
  process_name_i18n: discussion_templates.approve_a_document.process_name
  process_subtitle_i18n: discussion_templates.approve_a_document.process_subtitle
  process_introduction_i18n:  discussion_templates.approve_a_document.process_introduction
  description_i18n: discussion_templates.approve_a_document.description
  process_introduction_format: html
  description_format: html
  tags_i18n: 
  - doctypes.document
  newest_first: false
  position: 4
  max_depth: 3
  recipient_audience: group

share_links_and_info:
  title_placeholder_i18n: discussion_templates.share_links_and_info.title_placeholder
  process_name_i18n: discussion_templates.share_links_and_info.process_name
  process_subtitle_i18n: discussion_templates.share_links_and_info.process_subtitle
  process_introduction_i18n: discussion_templates.share_links_and_info.process_introduction
  description_i18n: discussion_templates.share_links_and_info.description
  tags_i18n: 
  - discussion_templates.share_links_and_info.information
  process_introduction_format: html
  description_format: html
  newest_first: true
  position: 3
  position: 6
  max_depth: 3
  recipient_audience: group

prepare_for_a_meeting:
  title_placeholder_i18n: discussion_templates.prepare_for_a_meeting.title_placeholder
  process_name_i18n: discussion_templates.prepare_for_a_meeting.process_name
  process_subtitle_i18n: discussion_templates.prepare_for_a_meeting.process_subtitle
  process_introduction_i18n: discussion_templates.prepare_for_a_meeting.process_introduction
  description_i18n: discussion_templates.prepare_for_a_meeting.description
  tags_i18n: 
  - decision_tools_card.meeting
  description_format: html
  process_introduction_format: html
  newest_first: false
  position: 4
  max_depth: 2
  recipient_audience: group

funding_decision:
  title_placeholder_i18n: discussion_templates.funding_decision.title_placeholder
  process_name_i18n: discussion_templates.funding_decision.process_name
  process_subtitle_i18n: discussion_templates.funding_decision.process_subtitle
  process_introduction_i18n: discussion_templates.funding_decision.process_introduction
  description_i18n: discussion_templates.funding_decision.description
  tags_i18n: 
  - decision_tools_card.meeting
  description_format: html
  process_introduction_format: html
  newest_first: false
  position: 4
  max_depth: 2
  recipient_audience: group

elect_a_governance_position:
  title_placeholder_i18n: discussion_templates.elect_a_governance_position.title_placeholder
  process_name_i18n: discussion_templates.elect_a_governance_position.process_name
  process_subtitle_i18n: discussion_templates.elect_a_governance_position.process_subtitle
  process_introduction_i18n: discussion_templates.elect_a_governance_position.process_introduction
  description_i18n: discussion_templates.elect_a_governance_position.description
  description_format: html
  tags_i18n: 
  - discussion_templates.elect_a_governance_position.election
  process_introduction_format: html
  newest_first: false
  position: 4
  max_depth: 2
  recipient_audience: group

build_a_policy:
  title_placeholder_i18n: discussion_templates.build_a_policy.title_placeholder
  process_name_i18n: discussion_templates.build_a_policy.process_name
  process_subtitle_i18n: discussion_templates.build_a_policy.process_subtitle
  process_introduction_i18n: discussion_templates.build_a_policy.process_introduction
  description_i18n: discussion_templates.build_a_policy.description
  description_format: html
  tags_i18n: 
  - discussion_templates.build_a_policy.policy
  process_introduction_format: html
  newest_first: false
  position: 4
  max_depth: 2
  recipient_audience: group
