supported:
  - ca
  - da
  - de
  - el
  - en
  - es
  - fi
  - fr
  - he
  - hr
  - hu
  - it
  - ja
  - nl_NL
  - pl
  - pt_BR
  - ro
  - ru
  - sl
  - sv
  - tr
  - uk
  - zh_TW
fallbacks:
  zh: zh_TW
  pt: pt_BR
  nl: nl_NL
