kinds:
  - reaction_created
  - comment_replied_to
  - user_mentioned
  - membership_requested
  - membership_request_approved
  - user_added_to_group
  - invitation_accepted
  - new_coordinator
  - poll_created
  - poll_closing_soon
  - poll_edited
  - poll_expired
  - poll_announced
  - outcome_created
  - outcome_announced
  - stance_created
  - poll_option_added
  - discussion_announced
  - group_announced
