loomio_org_plugin:
  repo:         https://github.com/loomio/loomio_org_plugin.git
  branch:       browserify

loomio_tags:
  repo:         https://github.com/loomio/loomio_tags.git
  branch:       browserify

loomio_truncate_comment:
  repo:         https://github.com/loomio/loomio_truncate_comment.git
  branch:       browserify

loomio_content_preview:
  repo:         https://github.com/loomio/loomio_content_preview.git
  branch:       browserify

loomio_onboarding:
  repo:         https://github.com/loomio/loomio_onboarding.git
  branch:       browserify
  # branch:       announcements
