loomio_webhooks:
  repo:         loomio/loomio_webhooks

loomio_org_plugin:
  repo:         loomio/loomio_org_plugin
  branch:       tests-for-sidebar-implementation

loomio_tags:
  repo:         loomio/loomio_tags
  branch:       to-production-and-beyond
  experimental: true
