loomio_webhooks:
  repo:         loomio/loomio_webhooks

loomio_org_plugin:
  repo:         loomio/loomio_org_plugin
  branch:       charge-for-subgroups

loomio_tags:
  repo:         loomio/loomio_tags
  branch:       prep-for-paid-feature

loomio_truncate_comment:
  repo:         loomio/loomio_truncate_comment
  experimental: true

loomio_content_preview:
  repo:         loomio/loomio_content_preview

loomio_buyer_experience:
  repo:         loomio/loomio_buyer_experience

loomio_onboarding:
  repo:         loomio/loomio_onboarding
  branch:       group-form-update
