loomio_tags:
  repo:         https://github.com/loomio/loomio_tags.git
  branch:       browserify-rails-5
loomio_truncate_comment:
  repo:         https://github.com/loomio/loomio_truncate_comment.git
  branch:       browserify

loomio_content_preview:
  repo:         https://github.com/loomio/loomio_content_preview.git
  branch:       browserify-rails-5
