proposal:
  poll_options_attributes:
    - name:                "agree"
    - name:                "abstain"
    - name:                "disagree"
    - name:                "block"
  chart_type:              pie
  material_icon:           mdi-thumbs-up-down
  has_option_icons:        true
  translate_option_name:   true
  can_remove_options:      true
  must_have_options:       false
  voters_review_responses: true
  require_stance_choices:  true
  can_vote_anonymously:    true
  single_choice:           true
  sort_options:
    - newest_first
    - oldest_first
    - priority_first
    - priority_last

count:
  poll_options_attributes:
    - name:               "yes"
    - name:               "no"
  chart_type:             progress
  material_icon:          mdi-check-circle
  has_option_icons:       true
  must_have_options:      true
  can_remove_options:     true
  require_stance_choices: true
  can_vote_anonymously:    true
  single_choice:          true
  sort_options:
    - newest_first
    - oldest_first
    - priority_first
    - priority_last

poll:
  poll_options_attributes: []
  chart_type:         bar
  material_icon:      mdi-poll
  can_add_options:    true
  can_remove_options: true
  must_have_options:  true
  can_vote_anonymously: true
  single_choice:      true
  sort_options:
    - newest_first
    - oldest_first

dot_vote:
  poll_options_attributes: []
  chart_type:              bar
  material_icon:           mdi-chart-bar-stacked
  can_add_options:         true
  can_remove_options:      true
  must_have_options:       true
  has_variable_score:      true
  can_vote_anonymously:    true
  required_custom_fields:
    - dots_per_person
  sort_options:
    - newest_first
    - oldest_first

score:
  poll_options_attributes: []
  chart_type:              bar
  material_icon:           mdi-chart-gantt
  can_add_options:         true
  can_remove_options:      true
  must_have_options:       true
  has_variable_score:      true
  can_vote_anonymously:    true
  required_custom_fields:
    - max_score
  sort_options:
    - newest_first
    - oldest_first

ranked_choice:
  poll_options_attributes: []
  chart_type:              bar
  material_icon:           mdi-format-list-numbered
  can_add_options:         true
  can_remove_options:      true
  must_have_options:       true
  require_stance_choices:  true
  has_variable_score:      true
  can_vote_anonymously:    true
  has_option_score_counts: true
  required_custom_fields:
    - minimum_stance_choices
  sort_options:
    - newest_first
    - oldest_first

meeting:
  poll_options_attributes: []
  chart_type:              matrix
  material_icon:           mdi-calendar-question
  can_add_options:         true
  can_remove_options:      true
  must_have_options:       true
  dates_as_options:        true
  author_receives_outcome: true
  has_variable_score:      true
  has_score_icons:         true
  prevent_anonymous:       true
  has_option_score_counts: true
  required_custom_fields:
    - can_respond_maybe
  sort_options:
    - newest_first
    - oldest_first
