proposal:
  poll_options_attributes:
    - name:              "agree"
    - name:              "abstain"
    - name:              "disagree"
    - name:              "block"
  has_option_icons:      true
  translate_option_name: true
  chart_type:            pie
  material_icon:         thumbs_up_down
  can_remove_options:    true
  must_have_options:     true
  voters_review_responses: true
  sort_options:
    - newest_first
    - oldest_first
    - priority_first
    - priority_last

count:
  poll_options_attributes:
    - name:           "yes"
    - name:           "no"
  translate_option_name: true
  has_option_icons:      true
  chart_type:         progress
  material_icon:      check_circle
  must_have_options:  true
  can_add_options:    false
  can_remove_options: false
  must_have_options:  true
  sort_options:
    - newest_first
    - oldest_first
    - priority_first
    - priority_last

poll:
  poll_options_attributes: []
  chart_type:         bar
  material_icon:      equalizer
  can_add_options:    true
  can_remove_options: true
  must_have_options:  true
  sort_options:
    - newest_first
    - oldest_first

dot_vote:
  poll_options_attributes: []
  chart_type:              bar
  material_icon:           grain
  can_add_options:         true
  can_remove_options:      true
  must_have_options:       true
  has_variable_score:      true

  # can we make this happen?
  # validates_custom_fields:
  #   dots_per_person:
  #     numericality:
  #       greater_than: 1

  required_custom_fields:
    - dots_per_person
    
  sort_options:
    - newest_first
    - oldest_first

meeting:
  poll_options_attributes: []
  chart_type:              matrix
  material_icon:           date_range
  can_add_options:         true
  can_remove_options:      true
  must_have_options:       true
  dates_as_options:        true
  sort_options:
    - newest_first
    - oldest_first
