# To customize periods and limits, simply add period or limit to the model's configuration, like so:
#
# group_creation:
#   route: (GROUP_ROUTE_REGEX)
#   period: 10
#   limit: 5
# (don't allow more than 5 group creations per 10 seconds)

# Methods will default to POST (usually used for object creation)
# to specify a different route, just add the 'method' key:
#
# group_visit:
#   route: (GROUP_ROUTE_REGEX)
#   method: GET
#   period: 60
#   limit: 5
# (don't allow more than 5 visits to a discussion per minute)
#
# NB: period is measured in seconds; (eg period: 120 = X requests per 2 minutes)

comment_creation:
  path: ^\/d\/[A-Za-z0-9]*\/add_comment$

group_creation:
  path: ^\/g$

discussion_creation:
  path: ^\/d$

motion_creation:
  path: ^\/m$

vote_creation:
  path: ^\/m\/[A-Za-z0-9]*\/votes$

default:
  period: 60
  limit: 10
  method: POST
