default: &default
  secret_key_base: <%= ENV['SECRET_COOKIE_TOKEN'] %>
  airbrake_api_key:  <%= ENV['AIRBRAKE_API_KEY'] %>
  devise: <%= ENV['DEVISE_SECRET'] %>
  google_key: <%= ENV['GOOGLE_KEY'] %>
  google_secret: <%= ENV['GOOGLE_SECRET'] %>
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  intercom_app_id: <%= ENV['INTERCOM_APP_ID'] %>
  intercom_app_secret: <%= ENV['INTERCOM_APP_SECRET'] %>
  intercom_app_api_key: <%= ENV['INTERCOM_APP_API_KEY'] %>
  omni_contacts_google_key: <%= ENV['OMNI_CONTACTS_GOOGLE_KEY'] %>
  omni_contacts_google_secret: <%= ENV['OMNI_CONTACTS_GOOGLE_SECRET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  enable_persona: <%= ENV['ENABLE_PERSONA'] || true %>
  custom_oauth2_name: <%= ENV['CUSTOM_OAUTH2_NAME'] %>
  custom_oauth2_key: <%= ENV['CUSTOM_OAUTH2_KEY'] %>
  custom_oauth2_secret: <%= ENV['CUSTOM_OAUTH2_SECRET'] %>
  custom_oauth2_site: <%= ENV['CUSTOM_OAUTH2_SITE'] %>
  custom_oauth2_authorize_url: <%= ENV['CUSTOM_OAUTH2_AUTHORIZE_URL'] %>
  custom_oauth2_token_url: <%= ENV['CUSTOM_OAUTH2_TOKEN_URL'] %>

development:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123

test:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123
  aws_access_key_id: fakeaccesskeyid
  aws_secret_access_key: fakesecretaccesskey
  aws_bucket: fakebucketname

staging:
  <<: *default

production:
  <<: *default
