default: &default
  max_message_length: <%= ENV.fetch('LMO_MAX_MESSAGE_LENGTH', 40000) %>
  secret_key_base: <%= ENV['SECRET_COOKIE_TOKEN'] %>
  devise: <%= ENV['DEVISE_SECRET'] %>
  google_key: <%= ENV['GOOGLE_KEY'] %>
  google_secret: <%= ENV['GOOGLE_SECRET'] %>
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  omni_contacts_google_key: <%= ENV['OMNI_CONTACTS_GOOGLE_KEY'] %>
  omni_contacts_google_secret: <%= ENV['OMNI_CONTACTS_GOOGLE_SECRET'] %>
  github_key: <%= ENV['GITHUB_APP_ID'] %>
  github_secret: <%= ENV['GITHUB_SECRET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  fog_provider: <%= ENV.fetch('FOG_PROVIDER', "Local") %>
  fog_uploads_directory: <%= ENV.fetch('FOG_UPLOADS_DIRECTORY', "uploads") %>
  canonical_host: <%= ENV['CANONICAL_HOST'] %>
  max_pending_emails: <%= ENV.fetch('MAX_PENDING_EMAILS', 30) %>

development:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123

test:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123
  chargify_app_name: loomio-test
  chargify_api_key: fakeapikey
  #aws_access_key_id: fakeaccesskeyid
  #aws_secret_access_key: fakesecretaccesskey
  #aws_bucket: fakebucketname

staging:
  <<: *default

production:
  <<: *default
