default: &default
  secret_key_base: <%= ENV['SECRET_COOKIE_TOKEN'] %>
  airbrake_api_key:  <%= ENV['AIRBRAKE_API_KEY'] %>
  devise: <%= ENV['DEVISE_SECRET'] %>
  google_key: <%= ENV['GOOGLE_KEY'] %>
  google_secret: <%= ENV['GOOGLE_SECRET'] %>
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  intercom_app_id: <%= ENV['INTERCOM_APP_ID'] %>
  intercom_app_secret: <%= ENV['INTERCOM_APP_SECRET'] %>
  intercom_app_api_key: <%= ENV['INTERCOM_APP_API_KEY'] %>
  omni_contacts_google_key: <%= ENV['OMNI_CONTACTS_GOOGLE_KEY'] %>
  omni_contacts_google_secret: <%= ENV['OMNI_CONTACTS_GOOGLE_SECRET'] %>
  github_key: <%= ENV['GITHUB_APP_ID'] %>
  github_secret: <%= ENV['GITHUB_SECRET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  fog_provider: <%= ENV.fetch('FOG_PROVIDER', "Local") %>
  fog_uploads_directory: <%= ENV.fetch('FOG_UPLOADS_DIRECTORY', "uploads") %>
  faye_url: <%= ENV['FAYE_URL'] %>
  canonical_host: <%= ENV['CANONICAL_HOST'] %>

development:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123

test:
  <<: *default
  secret_key_base: asjdahkjda
  devise: abc123
  chargify_app_name: loomio-test
  chargify_api_key: fakeapikey
  #aws_access_key_id: fakeaccesskeyid
  #aws_secret_access_key: fakesecretaccesskey
  #aws_bucket: fakebucketname

staging:
  <<: *default

production:
  <<: *default
