name: Publish Docker image

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAME: wizmoisa/loomio

jobs:
  build_and_push:
    name: Build and push ARM64 image
    runs-on: ubuntu-latest
    env:
      HAVESECRET: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ env.HAVESECRET == 'true' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ env.HAVESECRET == 'true' }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: ${{ env.HAVESECRET == 'true' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: wizmoisa/loomio

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v5
        if: ${{ env.HAVESECRET == 'true' }}
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
